Feat/challenge 03 loops conditionals
ZilongZhan/JavaScript-foundations-challenge-1 pull request #5
Opened 2023-10-31 19:29 UTC by ZilongZhan

2023-11-01 21:15 UTC, tictools requested changes

2023-11-01 21:15 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +  for (let i = 10; i <= 40; i++) {
Take care of naming.

```suggestion
  for (let index = 10; index <= 40; index++) {
```

2023-11-01 21:15 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +  for (let i = 10; i <= 40; i++) {
Same here regarding naming.

2023-11-01 21:15 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +  const randomNumber = Math.floor(Math.random() * (11 - 1) + 1);
```suggestion
  const randomNumber = Math.floor((Math.random() * 10) + 1)
```

2023-11-01 21:15 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +for (let i = 1; i <= 10; i++) {
Same here regarding naming. If `i` is storing an index, let's call it index.

2023-11-01 21:15 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +/* for (let i = 1; i <= 100; i++) {
Remove commented code. We never push commented code to production.

2023-11-01 21:15 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_00.js
> +  if (i == 3) {
```suggestion
   i++;
   
   if (i == 3) {
    loggedIn = true;
   } 
```

2023-11-01 21:15 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +    let message = i == 50 ? "Half way there!" : "You made it!";
Be careful with use of **not strict equal** comparision operator (take a look [here](https://github.com/DAW-EPIA-MAT/JavaScript-foundations#strict-equal-)) 

```suggestion
    let message = i === 50 ? "Half way there!" : "You made it!";
```

2023-11-01 21:21 UTC, ZilongZhan commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_01.js
> +  const randomNumber = Math.floor(Math.random() * (11 - 1) + 1);
Because of the nature of how Math.floor works, setting the value ceiling to 10 would basically inhibit 10 from ever being randomly generated. Do you still wish for it to be changed?

2023-11-01 21:34 UTC, ZilongZhan commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_00.js
> +  if (i == 3) {
If I increase the index value prior to it being evaluated in the conditional branches, the 'loggedIn' variable changes to true during the 3rd iteration of the loop, instead of after the 3rd iteration of the loop which is what the exercise was calling for.

Though I do agree that placing the index increment within an 'else' conditional is unnecessary in this case.

How should I proceed with this?

2023-11-07 19:33 UTC, Maarcfleckk commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +      console.log(`Number ${penis} is even`);
Line 13 needs work. Why did you name the variable like that?
Have you tested it before pushing?

2023-11-07 21:12 UTC, ZilongZhan commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +      console.log(`Number ${penis} is even`);
You are right I'm so sorry sir please don't hurt my family

2023-11-10 16:17 UTC, Maarcfleckk approved these changes

2023-11-10 18:24 UTC, tictools requested changes

2023-11-10 18:24 UTC, tictools commented on package.json
> +}
FIX: format code

2023-11-11 22:39 UTC, Maarcfleckk approved these changes

2023-11-12 06:34 UTC, tictools commented on package.json
> +}
@Maarcfleckk , good catch! Now that we know why this empty line is not in place, we can say... *format code, please*. 😉

2023-11-12 06:34 UTC, tictools approved these changes

2023-11-12 13:33 UTC, merged